### ISSUE TITLE
Open topics at root of devdocs project

### ISSUE THREAD

**Issue by jeff-matthews** [dobooth/devdocs_linker#1]
This works great @dobooth!

I noticed an issue with "versionless" topics that sit at the root of the devdocs project. Granted, we don't have a lot of those topics, but it would be cool if your extension could resolve those links as well.

For example, attempting to open `/extensions/amazon-sales/` throws an error:

<img width="431" alt="Screen Shot 2019-06-19 at 6 47 20 PM" src="https://user-images.githubusercontent.com/13662379/59808713-0fa10680-92c3-11e9-82be-332f990cb7a5.png">

**Comment by dobooth** [comment]
Fixed with version 0.2.
We now handle folders above /guides in devdocs, such as /cloud paths.
We now also fully support Merchdoc paths.
