### ISSUE TITLE
Nice Job!

### ISSUE THREAD

**Issue by bdenham** [dobooth/devdocs_linker#2]
I didn't know this existed! Good to know! Very convenient.

But it wouldn't be a repo without at least one issue! :)

Update your Readme to change the Defaults from 2.3 to 2.4. 

👍

**Comment by dobooth** [comment]
Good eye. Thanks for the feedback.
Fixed in https://github.com/dobooth/devdocs_linker/commit/e2dd2e9fd67a6c390261d8058fccc55b0ec82ab6.
